theme: jekyll-theme-hacker
title: Joel's homepage
description: A landing page for active projects, along with interests and other hobbies. 
markdown: kramdown

<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
